export const authConstant = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
};

export const bookAddingConstant = {
  ADDING_BOOK_REQUEST: 'ADDING_BOOK_REQUEST',
  ADDING_BOOK_SUCCESS: 'ADDING_BOOK_SUCCESS',
  ADDING_BOOK_FAILED: 'ADDING_BOOK_FAILED',
};

export const bookGettingConstant = {
  GETTING_BOOK_REQUEST: 'GETTING_BOOK_REQUEST',
  GEETING_BOOK_SUCCESS: 'GETTING_BOOK_SUCCESS',
  GETTING_BOOK_FAILED: 'GETTING_BOOK_FAILED',
};

export const editBookConstant = {
  EDIT_BOOK_REQUEST: 'EDIT_BOOK_REQUEST',
  EDIT_BOOK_SUCCESS: 'EDIT_BOOK_SUCCESS',
  EDIT_BOOK_FAILED: 'EDIT_BOOK_FAILED',
};

export const deleteBookConstant = {
  DELETE_BOOK_REQUEST: 'DELETE_BOOK_REQUEST',
  DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
  DELETE_BOOK_FAILED: 'DELETE_BOOK_FAILED',
};
