export const authConstant = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
};

export const bookAddingConstant = {
  ADDING_BOOK_REQUEST: 'ADDING_BOOK_REQUEST',
  ADDING_BOOK_SUCCESS: 'ADDING_BOOK_SUCCESS',
  ADDING_BOOK_FAILED: 'ADDING_BOOK_FAILED',
};

export const bookGettingConstant = {
  GETTING_BOOK_REQUEST: 'GETTING_BOOK_REQUEST',
  GEETING_BOOK_SUCCESS: 'GETTING_BOOK_SUCCESS',
  GETTING_BOOK_FAILED: 'GETTING_BOOK_FAILED',
};

export const editBookConstant = {
  EDIT_BOOK_REQUEST: 'EDIT_BOOK_REQUEST',
  EDIT_BOOK_SUCCESS: 'EDIT_BOOK_SUCCESS',
  EDIT_BOOK_FAILED: 'EDIT_BOOK_FAILED',
};

export const deleteBookConstant = {
  DELETE_BOOK_REQUEST: 'DELETE_BOOK_REQUEST',
  DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
  DELETE_BOOK_FAILED: 'DELETE_BOOK_FAILED',
};

export const manageUserConstant = {
  GET_USERS_REQUEST: 'GET_USER_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILED: 'GET_USERS_FAILED',
};

export const setReturnDateConstant = {
  SET_RETURN_DATE_REQUEST: 'SET_RETURN_DATE_REQUEST',
  SET_RETURN_DATE_SUCCESS: 'SET_RETURN_DATE_SUCCESS',
  SET_RETURN_DATE_FAILED: 'SET_RETURN_DATE_FAILED',
};

export const getReturnDateConstant = {
  GET_RETURN_DATE_REQUEST: 'GET_RETURN_DATE_REQUEST',
  GET_RETURN_DATE_SUCCESS: 'GET_RETURN_DATE_SUCCESS',
  GET_RETURN_DATE_FAILED: 'GET_RETURN_DATE_FAILED',
};

export const borrowBookConstant = {
  BORROW_BOOK_REQUEST: 'BORROW_BOOK_REQUEST',
  BORROW_BOOK_SUCCESS: 'BORROW_BOOK_SUCCESS',
  BORROW_BOOK_FAILED: 'BORROW_BOOK_FAILED',
};

export const reserveBookConstant = {
  RESERVE_BOOK_REQUEST: 'RESERVE_BOOK_REQUEST',
  RESERVE_BOOK_SUCCESS: 'RESERVE_BOOK_SUCCESS',
  RESERVE_BOOK_FAILED: 'RESERVE_BOOK_FAILED',
};

export const lowerBookQuanityConstant = {
  LOWER_BOOK_QUANITY_REQUEST: 'LOWER_BOOK_QUANITY_REQUEST',
  LOWER_BOOK_QUANITY_SUCCESS: 'LOWER_BOOK_QUANITY_SUCCESS',
  LOWER_BOOK_QUANITY_FAILED: 'LOWER_BOOK_QUANITY_FAILED',
};

export const getUserDataConstant = {
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILED: 'GET_USER_FAILED',
};

export const editUserDataConstant = {
  EDIT_USER_REQUEST: 'EDIT_USER_REQUEST',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILED: 'EDIT_USER_FAILED',
};
